import type { SubtitleTheme } from "@/types";

/**
 * Theme registry. Themes are pure data — the renderer (renderSubtitle.ts)
 * knows nothing about any specific theme. Adding a new theme never requires
 * touching the rendering engine.
 */
export const THEMES: SubtitleTheme[] = [
  {
    id: "minimal",
    name: "Minimal",
    font: "var(--font-inter)",
    fontSize: 56,
    fontWeight: 500,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: { color: "rgba(0,0,0,0.6)", width: 2 },
    shadow: { color: "rgba(0,0,0,0.35)", blur: 12, offsetX: 0, offsetY: 2 },
    background: null,
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "auto",
    positionStrategy: "auto",
  },
  {
    id: "bold",
    name: "Bold",
    font: "var(--font-archivo-black)",
    fontSize: 72,
    fontWeight: 900,
    textColor: "#ffffff",
    highlightColor: "#ffe600",
    stroke: { color: "#000000", width: 6 },
    shadow: { color: "rgba(0,0,0,0.5)", blur: 4, offsetX: 0, offsetY: 4 },
    background: null,
    animation: "pop",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "auto",
    positionStrategy: "auto",
  },
  {
    id: "karaoke",
    name: "Karaoke",
    font: "var(--font-poppins)",
    fontSize: 62,
    fontWeight: 700,
    textColor: "rgba(255,255,255,0.55)",
    highlightColor: "#22d3ee",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(0,0,0,0.4)", blur: 6, offsetX: 0, offsetY: 2 },
    background: null,
    animation: "highlight",
    wordHighlight: true,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "auto",
    positionStrategy: "auto",
  },
  {
    id: "pop",
    name: "Pop",
    font: "var(--font-baloo)",
    fontSize: 70,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#ff2d78",
    stroke: { color: "#1a0033", width: 5 },
    shadow: { color: "rgba(255,45,120,0.45)", blur: 18, offsetX: 0, offsetY: 0 },
    background: null,
    animation: "bounce",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "auto",
    positionStrategy: "auto",
    letterSpacing: 1,
  },
  {
    id: "gaming",
    name: "Gaming",
    font: "var(--font-russo-one)",
    fontSize: 68,
    fontWeight: 700,
    textColor: "#00ff9c",
    highlightColor: "#ffffff",
    stroke: { color: "#000000", width: 4 },
    shadow: { color: "#00ff9c", blur: 22, offsetX: 0, offsetY: 0 },
    background: null,
    animation: "scale",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "auto",
    letterSpacing: 1,
  },
  {
    id: "podcast",
    name: "Podcast",
    font: "var(--font-source-serif)",
    fontSize: 54,
    fontWeight: 600,
    textColor: "#f5f0e6",
    highlightColor: "#f5c542",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.6)", blur: 16, offsetX: 0, offsetY: 4 },
    background: { color: "rgba(20,16,10,0.72)", padding: 22, radius: 16 },
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-bottom",
  },
  {
    id: "neon",
    name: "Neon",
    font: "var(--font-russo-one)",
    fontSize: 66,
    fontWeight: 700,
    textColor: "#ffffff",
    highlightColor: "#ff00e5",
    stroke: { color: "#ff00e5", width: 2 },
    shadow: { color: "#00eaff", blur: 28, offsetX: 0, offsetY: 0 },
    background: null,
    animation: "pop",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "auto",
  },
  {
    id: "clean",
    name: "Clean",
    font: "var(--font-inter)",
    fontSize: 52,
    fontWeight: 600,
    textColor: "#111111",
    highlightColor: "#111111",
    stroke: undefined,
    shadow: undefined,
    background: { color: "rgba(255,255,255,0.92)", padding: 18, radius: 10 },
    animation: "none",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-bottom",
  },
  {
    id: "highlight",
    name: "Highlight",
    font: "var(--font-poppins)",
    fontSize: 60,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#0a0a0a",
    stroke: { color: "rgba(0,0,0,0.5)", width: 2 },
    shadow: { color: "rgba(0,0,0,0.35)", blur: 8, offsetX: 0, offsetY: 2 },
    background: null,
    animation: "highlight",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "auto",
    positionStrategy: "auto",
  },
  {
    id: "dynamic",
    name: "Dynamic",
    font: "var(--font-archivo-black)",
    fontSize: 64,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#ffd60a",
    stroke: { color: "#000000", width: 4 },
    shadow: { color: "rgba(0,0,0,0.4)", blur: 10, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "slide",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "auto",
  },

  // --- Reel-focused additions: bigger, louder, more "video editor" energy ---

  {
    id: "impact",
    name: "Impact",
    font: "var(--font-archivo-black)",
    fontSize: 84,
    fontWeight: 900,
    textColor: "#ffffff",
    highlightColor: "#ffe600",
    stroke: { color: "#000000", width: 8 },
    shadow: { color: "rgba(0,0,0,0.6)", blur: 2, offsetX: 0, offsetY: 6 },
    background: null,
    animation: "pop",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "front",
    positionStrategy: "auto",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    font: "var(--font-source-serif)",
    fontSize: 50,
    fontWeight: 600,
    textColor: "#f2f2f2",
    highlightColor: "#f2f2f2",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.7)", blur: 20, offsetX: 0, offsetY: 6 },
    background: { color: "rgba(0,0,0,0.55)", padding: 26, radius: 4 },
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-bottom",
    letterSpacing: 3,
  },
  {
    id: "glitch",
    name: "Glitch",
    font: "var(--font-russo-one)",
    fontSize: 68,
    fontWeight: 700,
    textColor: "#ffffff",
    highlightColor: "#05d9e8",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "#ff2a6d", blur: 12, offsetX: 0, offsetY: 0 },
    background: null,
    animation: "glitch",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "auto",
  },
  {
    id: "comic",
    name: "Comic",
    font: "var(--font-baloo)",
    fontSize: 74,
    fontWeight: 800,
    textColor: "#fff200",
    highlightColor: "#ff5ec4",
    stroke: { color: "#141414", width: 7 },
    shadow: { color: "rgba(0,0,0,0.4)", blur: 0, offsetX: 4, offsetY: 4 },
    background: null,
    animation: "bounce",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "auto",
    positionStrategy: "auto",
    letterSpacing: 1,
  },
  {
    id: "aurora",
    name: "Aurora",
    font: "var(--font-poppins)",
    fontSize: 66,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: undefined,
    shadow: { color: "rgba(139,92,246,0.5)", blur: 24, offsetX: 0, offsetY: 0 },
    background: null,
    animation: "wave",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "auto",
    positionStrategy: "auto",
    textGradient: ["#8b5cf6", "#06b6d4"],
  },
  {
    id: "vhs",
    name: "VHS",
    font: "var(--font-russo-one)",
    fontSize: 60,
    fontWeight: 700,
    textColor: "#ffe066",
    highlightColor: "#ff6b6b",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(255,255,255,0.25)", blur: 6, offsetX: 2, offsetY: 0 },
    background: null,
    animation: "typewriter",
    wordHighlight: true,
    dynamicWordSize: false,
    uppercase: true,
    depthMode: "front",
    positionStrategy: "fixed-bottom",
    letterSpacing: 2,
  },
  {
    id: "confetti",
    name: "Confetti",
    font: "var(--font-baloo)",
    fontSize: 68,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: { color: "#000000", width: 5 },
    shadow: { color: "rgba(0,0,0,0.35)", blur: 6, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "bounce",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "auto",
    positionStrategy: "auto",
    palette: ["#ff4d6d", "#ffd60a", "#06d6a0", "#4cc9f0", "#c77dff", "#ff9f1c"],
  },
  {
    id: "noir",
    name: "Noir",
    font: "var(--font-inter)",
    fontSize: 52,
    fontWeight: 600,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: { color: "rgba(0,0,0,0.8)", width: 2 },
    shadow: { color: "rgba(0,0,0,0.6)", blur: 10, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "typewriter",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-bottom",
    letterSpacing: 1,
  },

  // --- Reference-inspired additions: poster/editorial reel styles ---

  {
    id: "statement",
    name: "Statement",
    font: "var(--font-archivo-black)",
    fontSize: 78,
    fontWeight: 900,
    textColor: "#ffffff",
    highlightColor: "#ffd60a",
    stroke: { color: "#000000", width: 7 },
    shadow: { color: "rgba(0,0,0,0.55)", blur: 6, offsetX: 0, offsetY: 5 },
    background: null,
    animation: "pop",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "front",
    positionStrategy: "auto",
  },
  {
    id: "editorial",
    name: "Editorial",
    font: "var(--font-archivo-black)",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#ffffff",
    highlightColor: "#ffd60a",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.6)", blur: 10, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "scale",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-center",
  },
  {
    id: "quote",
    name: "Quote",
    font: "var(--font-source-serif)",
    fontSize: 56,
    fontWeight: 700,
    textColor: "#ffd166",
    highlightColor: "#ffffff",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.5)", blur: 14, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-center",
    letterSpacing: 0.5,
    italic: true,
  },
  {
    id: "script",
    name: "Script",
    font: "var(--font-caveat)",
    fontSize: 76,
    fontWeight: 700,
    textColor: "#ffd60a",
    highlightColor: "#ffffff",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "fade",
    wordHighlight: true,
    dynamicWordSize: false,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "auto",
  },
  {
    id: "trend",
    name: "Trend",
    font: "var(--font-poppins)",
    fontSize: 62,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(0,0,0,0.4)", blur: 4, offsetX: 0, offsetY: 2 },
    background: null,
    animation: "pop",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "auto",
    positionStrategy: "auto",
    palette: ["#ffffff", "#ff3b3b", "#ffd60a", "#ffffff"],
  },
  {
    id: "collage",
    name: "Collage",
    font: "var(--font-poppins)",
    fontSize: 58,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#e8261c",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(0,0,0,0.5)", blur: 6, offsetX: 0, offsetY: 2 },
    background: null,
    animation: "pop",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "auto",
    scatter: true,
  },
  {
    id: "callout",
    name: "Callout",
    font: "var(--font-poppins)",
    fontSize: 64,
    fontWeight: 800,
    textColor: "#ffffff",
    highlightColor: "#3ddc47",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "pop",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "front",
    positionStrategy: "auto",
    align: "left",
    colorByEmphasis: true,
  },
  {
    id: "colossal",
    name: "Colossal",
    font: "var(--font-anton)",
    fontSize: 110,
    fontWeight: 400,
    textColor: "#e0201b",
    highlightColor: "#e0201b",
    stroke: { color: "#000000", width: 8 },
    shadow: undefined,
    background: null,
    animation: "scale",
    wordHighlight: false,
    dynamicWordSize: false,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "fixed-center",
  },
  {
    id: "cascade",
    name: "Cascade",
    font: "var(--font-poppins)",
    fontSize: 58,
    fontWeight: 700,
    textColor: "#ffffff",
    highlightColor: "#ffffff",
    stroke: undefined,
    shadow: undefined,
    background: null,
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "fixed-center",
    align: "stairs",
    italic: true,
  },
  {
    id: "headline",
    name: "Headline",
    font: "var(--font-playfair-display)",
    fontSize: 80,
    fontWeight: 700,
    textColor: "#f3e3a3",
    highlightColor: "#f3e3a3",
    stroke: undefined,
    shadow: { color: "rgba(0,0,0,0.5)", blur: 10, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "fade",
    wordHighlight: false,
    dynamicWordSize: true,
    uppercase: false,
    depthMode: "front",
    positionStrategy: "auto",
    letterSpacing: 1,
  },
  {
    id: "marker",
    name: "Marker",
    font: "var(--font-luckiest-guy)",
    fontSize: 72,
    fontWeight: 400,
    textColor: "#ffffff",
    highlightColor: "#4fc3f7",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "rgba(0,0,0,0.45)", blur: 6, offsetX: 0, offsetY: 3 },
    background: null,
    animation: "pop",
    wordHighlight: true,
    dynamicWordSize: true,
    uppercase: true,
    depthMode: "behind_person",
    positionStrategy: "auto",
  },
];

export function getTheme(id: string): SubtitleTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export function applyThemeOverrides(
  theme: SubtitleTheme,
  overrides?: Partial<SubtitleTheme>
): SubtitleTheme {
  if (!overrides) return theme;
  return { ...theme, ...overrides };
}
